---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

# make sure namespace exists
resources:
- namespace.yaml

# custom index.html file


#vault helm chart
helmChartInflationGenerator:
- chartName: vault
  chartRepoUrl: https://grafana.github.io/helm-charts
  chartVersion: 5.30.0
  releaseName: loki
  releaseNamespace: loki
  # override with these custom values
  values: values.yaml

generatorOptions:
  disableNameSuffixHash: true

